export const SET_FACULTY = "SET_FACULTY";
export const FACULTY_UPDATE_PROFILE = "FACULTY_UPDATE_PROFILE";
export const FACULTY_GET_STUDENTS = "FACULTY_GET_STUDENTS";
export const FACULTY_GET_SUBJECT_CODE_LIST = "FACULTY_GET_SUBJECT_CODE_LIST";
export const FACULTY_HELPER = "FACULTY_HELPER";
export const FACULTY_UPLOAD_MARKS_GET_STUDENTS =
  "FACULTY_UPLOAD_MARKS_GET_STUDENTS";
export const FACULTY_UPLOAD_MARKS_GET_SUBJECT_CODE_LIST =
  "FACULTY_UPLOAD_MARKS_GET_SUBJECT_CODE_LIST";
export const FACULTY_UPLOAD_MARKS_HELPER = "FACULTY_UPLOAD_MARKS_HELPER";
export const FACULTY_GET_STUDENTS_ATTENDANCE =
  "FACULTY_GET_STUDENTS_ATTENDANCE";
export const FACULTY_GET_STUDENTS_MARKS = "FACULTY_GET_STUDENTS_MARKS";
