export const SET_STUDENT = "SET_STUDENT";
export const STUDENT_UPDATE_PROFILE = "STUDENT_UPDATE_PROFILE";
export const STUDENT_GET_ATTENDANCE = "STUDENT_GET_ATTENDANCE";
export const STUDENT_GET_MARKS = "STUDENT_GET_MARKS";
export const STUDENT_LOGOUT = "STUDENT_LOGOUT";
